spring: 
  datasource:
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver 
    #username: sa
    #password: 
    url: jdbc:mysql://localhost:3306/testDB?createDatabaseIfNotExist=true
    username: root
    password: Passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
